### ISSUE TITLE
How to generate BTF file for a specific kernel?

### ISSUE THREAD

**Issue by nurdann** [aquasecurity/btfhub-archive#2]
I am trying to follow https://github.com/rafaeldtinoco/portablebpf/tree/v4.15-kernels 

I have ran,
```
sudo apt-get install linux-image-4.15.0-139-generic linux-headers-4.15.0-139-generic linux-modules-4.15.0-139-generic linux-modules-extra-4.15.0-139-generic linux-image-4.15.0-139-generic-dbgsym
```

And rebooted into new kernel
```
$ uname -r
4.15.0-139-generic
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.7 LTS
Release:	16.04
Codename:	xenial
```

When I apply `pahole` I get (it modifies the supplied file?),
```
$ cp /usr/lib/debug/boot/vmlinux-4.15.0-139-generic .
$ sudo pahole -J vmlinux-4.15.0-139-generic 
btf_elf__write: failed to add .BTF section to 'vmlinux-4.15.0-139-generic': 12!
Failed to encode BTF
```

Here is `pahole` version,
```
$ pahole --version
v1.21
```

If successful, is it also possible to do the same for kernel 4.4? Currently, deciding to go with python-bcc or libbpf.

**Comment by rafaeldtinoco** [comment]
Hum, what about if you try to encode an external raw BTF file ? Does it work ?

For v4.4, check https://github.com/iovisor/bcc/blob/master/docs/kernel-versions.md... you might be missing lots of eBPF features in that version.

**Comment by nurdann** [comment]
How to encode an external raw BTF file?
