### ISSUE TITLE
Compatibility of BTFs with different minor kernel versions

### ISSUE THREAD

**Issue by zhuozl** [aquasecurity/btfhub-archive#3]
Is there another version of BTF with a different kernel? For example, 4.19.12-1.el7.elrepo.x86_64.
Will other existing 4.19.xx be compatible with this version?

**Comment by rafaeldtinoco** [comment]
@zhuozl probably not,

The BTF file is a file that expresses the types used for a specific kernel source code (including major, minor and included patches). Different kernels usually have different minor (or different patches applied).

The BTF file would only be compatible if both kernels had the same patchset level (I doubt) and were build with the same kconfig file (I also doubt).

There is a chance that the BTF file will work, but there is definitely no guarantees.

> You can propose changes to BTFHUB script responsible for downloading and generating the BTF files (as other projects did, when including debian and amzn2).

**Comment by rafaeldtinoco** [comment]
Changes would go here: https://github.com/aquasecurity/btfhub/blob/main/tools/update.sh

**Comment by rafaeldtinoco** [comment]
I'm closing this (and issues within this repository) as I'm working only with issues in the main repository (and this is an archive repository only). Would you mind opening the issue there ? Either way, I'm working on it.
