### ISSUE TITLE
Could you help add the license file to this project?

### ISSUE THREAD

**Issue by mrproliu** [aquasecurity/btfhub-archive#4]
Hello, I am from the [Apache SkyWalking](https://github.com/apache/skywalking) community. By reading [this blog](https://kinvolk.io/blog/2022/03/btfgen-one-step-closer-to-truly-portable-ebpf-programs/), I learned that BTFGen can make eBPF programs portable. This is a great idea, and we'd love to add it to our [SkyWalking Rover](https://github.com/apache/skywalking-rover) project.
However, during the integration, we found that the [btfhub-archive](https://github.com/aquasecurity/btfhub-archive) project did not add the `LICENSE` file, so we could not add it to the binary LICENSE statement file. So, could we help add the license file to this project?

You could get more information [through this PR](https://github.com/apache/skywalking-rover/pull/35). Hope to get your reply, thanks!

**Comment by rafaeldtinoco** [comment]
Hello @mrproliu, 

Yes, the license of this repository is the same as btfhub repository. I haven't added it here because this is an archive only repository. Let me see if adding a LICENSE file here won't break any of our builds.

**Comment by rafaeldtinoco** [comment]
I'm closing this (and issues within this repository) as I'm working only with issues in the main repository (and this is an archive repository only). Would you mind opening the issue there ? Either way, I'm working on it.
